# Generated by Django 3.2.12 on 2022-03-22 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='guest_can_skip',
            new_name='votes_to_skip',
        ),
    ]
